root_folder: machine-learning-6911

mongodb:
  is_cloud: 0
  user_name: test
  password: test
  url: mongodb+srv://{0}:{1}@cluster0.zdrmj.mongodb.net/test?authSource=admin&replicaSet=atlas-z2zcir-shard-0&readPreference=primary&appname=MongoDB%20Compass&ssl=true

cloud_storage:
  azure_blob_storage:
    connection_str: DefaultEndpointsProtocol=https;AccountName=mldeploy1;AccountKey=H2D+ItTForoqg2xAxg43OpPkEP5fj0/ZnpLA5nlfHD3dggMOEurpv+lPewKgKFyEC2ycHA3Fco95RR4uNXSTOQ==;EndpointSuffix=core.windows.net
  aws_s3_bucket:
    name: aws_access_key
    Access Key ID: AKIA3GUOOKFCKETYPHW4
    Secret Access Key: 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
    description: AWS credentials

  gcp: gcp.json

watcher_checkpoint_storage_account_connection_str:
  connection_str: DefaultEndpointsProtocol=https;AccountName=storageaccountrgai1a757;AccountKey=j4TYtRYwIDyUNL4lKXXIfYgCftrTbJPhPHC8i/j66XSf6s81ruCaQqDnjh5WDMjrqqc4hulvZ8wxcYQb8KfukA==;EndpointSuffix=core.windows.net

azure_input_file_storage_connection_str:
  connection_str: DefaultEndpointsProtocol=https;AccountName=inputfilestorage;AccountKey=u2jUt3DLgsPiZO8S7kZ1yk4B7FJ6gCtdTeckaige1AXTnyPA1zby1w0n6HUi/2cdOAoo5E1jXrEeofyI6UDtFw==;EndpointSuffix=core.windows.net

event_hub_name_space:
  connection_str: Endpoint=sb://avnish327030.servicebus.windows.net/;SharedAccessKeyName=RootManageSharedAccessKey;SharedAccessKey=BwK0zozJe+Oz46F5BgpHUtq5zkzqMKCzPdc2kOg2WW8=


session:
  secret-key: ec6935d1-0e2c-4998-b7ed-809e8cb0fcda

user_detail:
  email_id: abid.colab@gmail.com
  role_id: 1 #1 for adming, 2 for viewer

email_config:
  sender_email_id: abidghias89@gmail.com
  passkey: eswbtarwlvcwdbow
  receiver_email_id:
    - abid.colab@gmail.com
    - anishyadav7045075175@gmail.com