# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy container app to Azure Web App - cloudML-345

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: 'ubuntu-latest'

    steps:
    - uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Log in to registry
      uses: docker/login-action@v1
      with:
        registry: https://index.docker.io/v1/
        username: ${{ secrets.AzureAppService_ContainerUsername_322e9a0a3b4f4813be0a07615ba7af34 }}
        password: ${{ secrets.AzureAppService_ContainerPassword_07c2751371f541c5881fdf8897490c64 }}

    - name: Build and push container image to registry
      uses: docker/build-push-action@v2
      with:
        push: true
        tags: index.docker.io/${{ secrets.AzureAppService_ContainerUsername_322e9a0a3b4f4813be0a07615ba7af34 }}/cloudML-345:${{ github.sha }}
        file: ./Dockerfile

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
    - name: Deploy to Azure Web App
      id: deploy-to-webapp
      uses: azure/webapps-deploy@v2
      with:
        app-name: 'cloudML-345'
        slot-name: 'production'
        publish-profile: ${{ secrets.AzureAppService_PublishProfile_257eef8c6c2c4156be7ad4816de82282 }}
        images: 'index.docker.io/${{ secrets.AzureAppService_ContainerUsername_322e9a0a3b4f4813be0a07615ba7af34 }}/cloudML-345:${{ github.sha }}'